### ISSUE TITLE
image error

### ISSUE THREAD

**Issue by Rahul-Chouhan-wolf** [xpd54/Car-race-game#2]
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:/Users/Lucifer/Desktop/py/game.py", line 61, in <module>
    car3 = pygame.image.load('image/car3.png')
pygame.error: Couldn't open image/car3.png

**Comment by xpd54** [comment]
@Rahul-Chouhan-wolf Recently I run this old project on mac with paython3. Worked in one go. I am happy to help if still curious.
